package com.arcsoft.sdk_demo.utils.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.arcsoft.sdk_demo.utils.bean.PrisonerInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRISONER_INFO".
*/
public class PrisonerInfoDao extends AbstractDao<PrisonerInfo, Long> {

    public static final String TABLENAME = "PRISONER_INFO";

    /**
     * Properties of entity PrisonerInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Crime_id = new Property(1, String.class, "crime_id", false, "CRIME_ID");
        public final static Property Crime_name = new Property(2, String.class, "crime_name", false, "CRIME_NAME");
        public final static Property Crime_jianqu = new Property(3, String.class, "crime_jianqu", false, "CRIME_JIANQU");
        public final static Property Crime_xb = new Property(4, String.class, "crime_xb", false, "CRIME_XB");
        public final static Property Crime_featuredata = new Property(5, String.class, "crime_featuredata", false, "CRIME_FEATUREDATA");
    }


    public PrisonerInfoDao(DaoConfig config) {
        super(config);
    }
    
    public PrisonerInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRISONER_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CRIME_ID\" TEXT," + // 1: crime_id
                "\"CRIME_NAME\" TEXT," + // 2: crime_name
                "\"CRIME_JIANQU\" TEXT," + // 3: crime_jianqu
                "\"CRIME_XB\" TEXT," + // 4: crime_xb
                "\"CRIME_FEATUREDATA\" TEXT);"); // 5: crime_featuredata
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRISONER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PrisonerInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String crime_id = entity.getCrime_id();
        if (crime_id != null) {
            stmt.bindString(2, crime_id);
        }
 
        String crime_name = entity.getCrime_name();
        if (crime_name != null) {
            stmt.bindString(3, crime_name);
        }
 
        String crime_jianqu = entity.getCrime_jianqu();
        if (crime_jianqu != null) {
            stmt.bindString(4, crime_jianqu);
        }
 
        String crime_xb = entity.getCrime_xb();
        if (crime_xb != null) {
            stmt.bindString(5, crime_xb);
        }
 
        String crime_featuredata = entity.getCrime_featuredata();
        if (crime_featuredata != null) {
            stmt.bindString(6, crime_featuredata);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PrisonerInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String crime_id = entity.getCrime_id();
        if (crime_id != null) {
            stmt.bindString(2, crime_id);
        }
 
        String crime_name = entity.getCrime_name();
        if (crime_name != null) {
            stmt.bindString(3, crime_name);
        }
 
        String crime_jianqu = entity.getCrime_jianqu();
        if (crime_jianqu != null) {
            stmt.bindString(4, crime_jianqu);
        }
 
        String crime_xb = entity.getCrime_xb();
        if (crime_xb != null) {
            stmt.bindString(5, crime_xb);
        }
 
        String crime_featuredata = entity.getCrime_featuredata();
        if (crime_featuredata != null) {
            stmt.bindString(6, crime_featuredata);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PrisonerInfo readEntity(Cursor cursor, int offset) {
        PrisonerInfo entity = new PrisonerInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // crime_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // crime_name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // crime_jianqu
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // crime_xb
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // crime_featuredata
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PrisonerInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCrime_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCrime_name(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCrime_jianqu(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCrime_xb(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCrime_featuredata(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PrisonerInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PrisonerInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PrisonerInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
